[[lrslib]]
arch = "aarch64"
git-tree-sha1 = "f63908012def8a8a02926799ec136f3ceabfa4e7"
libc = "glibc"
os = "linux"

    [[lrslib.download]]
    sha256 = "ce8a7f6537279bbae4de543a662ea2a13c018cfc2e854126fe0bbbbb014ca220"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.3.1+0/lrslib.v0.3.1.aarch64-linux-gnu.tar.gz"
[[lrslib]]
arch = "aarch64"
git-tree-sha1 = "743c3d885cfc4843b87ab182ac050aabd1abefb9"
libc = "musl"
os = "linux"

    [[lrslib.download]]
    sha256 = "416175f9fe3615083366f1a7d7c7df85d1ba35133faa12c995b22a23d90d81bd"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.3.1+0/lrslib.v0.3.1.aarch64-linux-musl.tar.gz"
[[lrslib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c461de0b7d2cc34af1f012ce428b8abc78efa0eb"
libc = "glibc"
os = "linux"

    [[lrslib.download]]
    sha256 = "e5052b69149ce8dcedaf6ad1d15f74f1d2479d8565b17ea7c646d32523332b59"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.3.1+0/lrslib.v0.3.1.armv7l-linux-gnueabihf.tar.gz"
[[lrslib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6ddc0307d315e437eb2cd5546dc293b8171193db"
libc = "musl"
os = "linux"

    [[lrslib.download]]
    sha256 = "885a96e7b268c29b7517776d585e6ecd135dcd8d88fd9e217098e325523f3321"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.3.1+0/lrslib.v0.3.1.armv7l-linux-musleabihf.tar.gz"
[[lrslib]]
arch = "i686"
git-tree-sha1 = "2642f9b1eea4cec1775fef8be0a68ecb60b0f215"
libc = "glibc"
os = "linux"

    [[lrslib.download]]
    sha256 = "5dad3b970fb57ed4f84429a5f0c2ef7505e7811828da4da1d0f0154ab6244937"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.3.1+0/lrslib.v0.3.1.i686-linux-gnu.tar.gz"
[[lrslib]]
arch = "i686"
git-tree-sha1 = "f44e53ee2f25064570901fc614d733bf261d5a19"
libc = "musl"
os = "linux"

    [[lrslib.download]]
    sha256 = "8ff95450ee436f70618943ad89f6e670abdae2a5aabda12203bd67158b5e185a"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.3.1+0/lrslib.v0.3.1.i686-linux-musl.tar.gz"
[[lrslib]]
arch = "i686"
git-tree-sha1 = "67981e4788edcc9bc0a33a01e81d045f7c364b5b"
os = "windows"

    [[lrslib.download]]
    sha256 = "3ba4f451142a5c5c383832a7dc8fb9feb8c7c8ef77657c49c123bdf045e6773b"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.3.1+0/lrslib.v0.3.1.i686-w64-mingw32.tar.gz"
[[lrslib]]
arch = "powerpc64le"
git-tree-sha1 = "c0ba836a4c9e0351e3ada5ab617cbad3742fef0c"
libc = "glibc"
os = "linux"

    [[lrslib.download]]
    sha256 = "a0828ccdbe4e33543a0b2d20e151c76fa4c8661eb93f415f2312cbf1a416040c"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.3.1+0/lrslib.v0.3.1.powerpc64le-linux-gnu.tar.gz"
[[lrslib]]
arch = "x86_64"
git-tree-sha1 = "e449e575ab04b1a5872699a45a5781e324218b20"
os = "macos"

    [[lrslib.download]]
    sha256 = "1281e14ba100aa60c83cef3dd683fba0749d8c99d59a7d542b1e695026dc35dc"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.3.1+0/lrslib.v0.3.1.x86_64-apple-darwin.tar.gz"
[[lrslib]]
arch = "x86_64"
git-tree-sha1 = "9b129209d6ea3f8797eff321f6a1694d08814c51"
libc = "glibc"
os = "linux"

    [[lrslib.download]]
    sha256 = "cb8e3fdb7ed850df40786c0cd91247cf618a9fd1e3b54805af6cfc1379fd5207"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.3.1+0/lrslib.v0.3.1.x86_64-linux-gnu.tar.gz"
[[lrslib]]
arch = "x86_64"
git-tree-sha1 = "79a5f972a5b043137391e59046ad7b48f8372c97"
libc = "musl"
os = "linux"

    [[lrslib.download]]
    sha256 = "c64d5625cd7696f334ff402809e5b412c7a080d6abc198e62cc4fa8c784b912e"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.3.1+0/lrslib.v0.3.1.x86_64-linux-musl.tar.gz"
[[lrslib]]
arch = "x86_64"
git-tree-sha1 = "d72b439947ccf327e80b8176b941c420db37dffb"
os = "freebsd"

    [[lrslib.download]]
    sha256 = "29937630507d042abb7822b0a8dba598fedb399281cd8ec64ce203ae27512f7d"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.3.1+0/lrslib.v0.3.1.x86_64-unknown-freebsd.tar.gz"
[[lrslib]]
arch = "x86_64"
git-tree-sha1 = "f95d8f47f8b94244ad1ed3b7ceada5a67f9d2226"
os = "windows"

    [[lrslib.download]]
    sha256 = "fe64dfd80cfd50ea930a088c0fe8ddc87e59504e01dae9d9555dd707fbff9c8d"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.3.1+0/lrslib.v0.3.1.x86_64-w64-mingw32.tar.gz"
