[[lrslib]]
arch = "aarch64"
git-tree-sha1 = "b81552950f6f598d53626e662288b173d6e311f0"
libc = "musl"
os = "linux"

    [[lrslib.download]]
    sha256 = "6dbf12cf182f29c9cd15c21a1a21d0369b5106b724b7e4c0e526f6ec05823718"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+0/lrslib.v0.1.0.aarch64-linux-musl.tar.gz"
[[lrslib]]
arch = "aarch64"
git-tree-sha1 = "a3ec15502ffbd16d22087184d944a4cbb8dbef4c"
libc = "glibc"
os = "linux"

    [[lrslib.download]]
    sha256 = "9b93203d33a2d57c20f474ad2f861d6ebe098d01556e5dcc162640f39169dbfd"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+0/lrslib.v0.1.0.aarch64-linux-gnu.tar.gz"
[[lrslib]]
arch = "x86_64"
git-tree-sha1 = "8ce7aef7015123545974e317c13d2d8c62a9bea5"
libc = "glibc"
os = "linux"

    [[lrslib.download]]
    sha256 = "f88cc62b6a595b7c3a04c79d764f58a04bfc4086356407b615182b5b9839c7da"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+0/lrslib.v0.1.0.x86_64-linux-gnu.tar.gz"
[[lrslib]]
arch = "powerpc64le"
git-tree-sha1 = "ca1e148a7eb08bb5d2aac835ba921c52191deeff"
libc = "glibc"
os = "linux"

    [[lrslib.download]]
    sha256 = "0a0e04f4cd94ed370ee58ac43e7460b9a134654061f1561008f9767e5dc1581e"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+0/lrslib.v0.1.0.powerpc64le-linux-gnu.tar.gz"
[[lrslib]]
arch = "x86_64"
git-tree-sha1 = "08bdb23a4b0df4cbc3139f0ef7f86b6630437242"
os = "freebsd"

    [[lrslib.download]]
    sha256 = "5184a813ce8c1f69cad35bb125eaf6675a774920b4d35e43675160ca149c1187"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+0/lrslib.v0.1.0.x86_64-unknown-freebsd11.1.tar.gz"
[[lrslib]]
arch = "x86_64"
git-tree-sha1 = "87b7d28ac4caef2f626503ce6e58358d1d06a006"
libc = "musl"
os = "linux"

    [[lrslib.download]]
    sha256 = "a5b2cdcf3c2a1b55e788f1b9f9c60e0b33d93f36022f9d0fb89c68e4dea7e56b"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+0/lrslib.v0.1.0.x86_64-linux-musl.tar.gz"
