[[lrslib]]
arch = "aarch64"
git-tree-sha1 = "33a39e3dfbe4663724b72a512fc658591c59050c"
libc = "musl"
os = "linux"

    [[lrslib.download]]
    sha256 = "20ad884a1a67e30ca68fe14462d0aeec1630662a12ba53d25a018b9cb52b5a50"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+1/lrslib.v0.1.0.aarch64-linux-musl.tar.gz"
[[lrslib]]
arch = "i686"
git-tree-sha1 = "5e8344c78f600ea197234652949ab26ef15ff90f"
os = "windows"

    [[lrslib.download]]
    sha256 = "ac7f9035faaba79e68eb005fe1cc487d773401656b38b2bf0fd1690fcfd1210f"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+1/lrslib.v0.1.0.i686-w64-mingw32.tar.gz"
[[lrslib]]
arch = "x86_64"
git-tree-sha1 = "c0fb92905759309548e55244c1e673de07317ae6"
libc = "musl"
os = "linux"

    [[lrslib.download]]
    sha256 = "67e21c93a94176eccabc0b8a48ebb69b8583a5e8d5afdefa274b516c6985f9ff"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+1/lrslib.v0.1.0.x86_64-linux-musl.tar.gz"
[[lrslib]]
arch = "i686"
git-tree-sha1 = "7ae78a9d5949685234d77ddf5443be346348b6ea"
libc = "glibc"
os = "linux"

    [[lrslib.download]]
    sha256 = "c0ac0df7b4898ebd90a525ebfe766cf2ab46d4c7b6c6fbb43337ebea3678414c"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+1/lrslib.v0.1.0.i686-linux-gnu.tar.gz"
[[lrslib]]
arch = "armv7l"
git-tree-sha1 = "734f5a2e5080311c60881c464c43b0b586f569d8"
libc = "glibc"
os = "linux"

    [[lrslib.download]]
    sha256 = "a32f755e2bb2cb444bfd364381c396a2c17ca5683cd3443668ab6f28e251f102"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+1/lrslib.v0.1.0.armv7l-linux-gnueabihf.tar.gz"
[[lrslib]]
arch = "aarch64"
git-tree-sha1 = "41f1c090bea3d9dda172b2662fc406761318c25b"
libc = "glibc"
os = "linux"

    [[lrslib.download]]
    sha256 = "28e369392863ad7261cd7c356a9d5c6f58723f50a22d57774f3512b444093831"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+1/lrslib.v0.1.0.aarch64-linux-gnu.tar.gz"
[[lrslib]]
arch = "x86_64"
git-tree-sha1 = "038aa16d78d66cc3b7237b851f19e7629c5f4e66"
libc = "glibc"
os = "linux"

    [[lrslib.download]]
    sha256 = "5be9dee89a6079be9f7d18c76a8175397aae24c827b5a5f603f3c1961b7c9baa"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+1/lrslib.v0.1.0.x86_64-linux-gnu.tar.gz"
[[lrslib]]
arch = "powerpc64le"
git-tree-sha1 = "4be0f8775f7d8917d15af89eeb2701d081a3bed2"
libc = "glibc"
os = "linux"

    [[lrslib.download]]
    sha256 = "d71bf2837d9c313b9d160dd5a6c0fbf84d5949a9d360388a317a08826c421c23"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+1/lrslib.v0.1.0.powerpc64le-linux-gnu.tar.gz"
[[lrslib]]
arch = "x86_64"
git-tree-sha1 = "4b2fec4e7ae660644b530bdd32558397df21bbb6"
os = "macos"

    [[lrslib.download]]
    sha256 = "a41acf7fdec264f41718bb2c7ad59b07c9099dd60d8b9df083b1f155281da181"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+1/lrslib.v0.1.0.x86_64-apple-darwin14.tar.gz"
[[lrslib]]
arch = "x86_64"
git-tree-sha1 = "e36c695dc5a124a9a43fba1c89091572afc42bf8"
os = "freebsd"

    [[lrslib.download]]
    sha256 = "33a84dd868a977c70f04368831fe8acf66d7ab373f086bbe5a5ba454bec6a676"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+1/lrslib.v0.1.0.x86_64-unknown-freebsd11.1.tar.gz"
[[lrslib]]
arch = "i686"
git-tree-sha1 = "38c36fc6b9c3ddd337a56c1c79649df578afac3a"
libc = "musl"
os = "linux"

    [[lrslib.download]]
    sha256 = "321f9c933a3c158c1eb282fe4f2e1c2e6a60a3cd17f15ac64fbe6ae1c9f4395e"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+1/lrslib.v0.1.0.i686-linux-musl.tar.gz"
[[lrslib]]
arch = "armv7l"
git-tree-sha1 = "e703ea2ab20aea657c3593bdcf1bbf774518619a"
libc = "musl"
os = "linux"

    [[lrslib.download]]
    sha256 = "794b31c94970dbf40c26f33ac161ee99174922143d429ab4aa61a6576bb1edc4"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+1/lrslib.v0.1.0.armv7l-linux-musleabihf.tar.gz"
[[lrslib]]
arch = "x86_64"
git-tree-sha1 = "0c1d999bd88dd1708dd2995a64087e15939646a0"
os = "windows"

    [[lrslib.download]]
    sha256 = "76c3c1e7c95b1c7afa09aefb6548e1cecafc8262bb9a63146124e302d546b016"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+1/lrslib.v0.1.0.x86_64-w64-mingw32.tar.gz"
