[[lrslib]]
arch = "aarch64"
git-tree-sha1 = "6d100208d8030c7d533111c59064c2e8c726cea8"
libc = "glibc"
os = "linux"

    [[lrslib.download]]
    sha256 = "afde991f2ccdae1331f91c75bfa6d97a3e10aada4f50c94423b54b146700082a"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.2.0+0/lrslib.v0.2.0.aarch64-linux-gnu.tar.gz"
[[lrslib]]
arch = "aarch64"
git-tree-sha1 = "90775b0d77dc9413863880b1e43302df5f444a5f"
libc = "musl"
os = "linux"

    [[lrslib.download]]
    sha256 = "1057c69f25742ed0d1c0e539dc868f85a96a25d64fe58d017e5931590d2f97f7"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.2.0+0/lrslib.v0.2.0.aarch64-linux-musl.tar.gz"
[[lrslib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f5df40c6cdc310214b45930fa589cb66ad307e6c"
libc = "glibc"
os = "linux"

    [[lrslib.download]]
    sha256 = "4f1b929b585ea3cc8addcebc0f385b80f7b96554cb35e2bf30af439bf9f31f2c"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.2.0+0/lrslib.v0.2.0.armv7l-linux-gnueabihf.tar.gz"
[[lrslib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "99feffbf732a975727f0945ecfebacaa9c2d386f"
libc = "musl"
os = "linux"

    [[lrslib.download]]
    sha256 = "7980470ac181a428fe9776be9a50bee08745b2f76f77ebd4a93c6c13df434cee"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.2.0+0/lrslib.v0.2.0.armv7l-linux-musleabihf.tar.gz"
[[lrslib]]
arch = "i686"
git-tree-sha1 = "088e4d1a535e265d1877aff33b0d77d29f7a0798"
libc = "glibc"
os = "linux"

    [[lrslib.download]]
    sha256 = "11e6da1c107c98e95c1795920345c813d8860d235f8cc70ce712ecbc1bf7e4d5"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.2.0+0/lrslib.v0.2.0.i686-linux-gnu.tar.gz"
[[lrslib]]
arch = "i686"
git-tree-sha1 = "98677a9745a392ac8d1bc8f8e363847a53f459ba"
libc = "musl"
os = "linux"

    [[lrslib.download]]
    sha256 = "17638864762882b72b6c61268ed7c0f54562df6dbcd7d5aa54376e2020f743e4"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.2.0+0/lrslib.v0.2.0.i686-linux-musl.tar.gz"
[[lrslib]]
arch = "i686"
git-tree-sha1 = "7bc594f88394e75e34a578303ce9599974b30810"
os = "windows"

    [[lrslib.download]]
    sha256 = "0dfc7041caef6564d2e35624ac0bda882f356d91950002bd406113f5057a68f6"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.2.0+0/lrslib.v0.2.0.i686-w64-mingw32.tar.gz"
[[lrslib]]
arch = "powerpc64le"
git-tree-sha1 = "0fc6e33e05b2025a6bd9406d1e26383b89d08d9f"
libc = "glibc"
os = "linux"

    [[lrslib.download]]
    sha256 = "96bfcf45b2ebd8ac1bcdb49ecae83626d7c49edabeca6f58caf07f328e1bd412"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.2.0+0/lrslib.v0.2.0.powerpc64le-linux-gnu.tar.gz"
[[lrslib]]
arch = "x86_64"
git-tree-sha1 = "b690e9082f57fc15a7f9b0c1804204d49cc76085"
os = "macos"

    [[lrslib.download]]
    sha256 = "3a0cdf0b18515a8d86d957d07f1b84400c5060b5df45243796b5b23cea5e54ae"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.2.0+0/lrslib.v0.2.0.x86_64-apple-darwin.tar.gz"
[[lrslib]]
arch = "x86_64"
git-tree-sha1 = "8d0503febedd2202cb73e7696cc874a6cf68129c"
libc = "glibc"
os = "linux"

    [[lrslib.download]]
    sha256 = "ecd7f7400967df9923afdc9a804b52e3cb483d215f47705c2efaa4144c5b09ce"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.2.0+0/lrslib.v0.2.0.x86_64-linux-gnu.tar.gz"
[[lrslib]]
arch = "x86_64"
git-tree-sha1 = "2253ee22cc1e0f8ba01acaf23c2526da18c0def3"
libc = "musl"
os = "linux"

    [[lrslib.download]]
    sha256 = "a5a6b005dda1df7731d1348fc4312d1c45f80fbf8b44f447da364883127426bc"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.2.0+0/lrslib.v0.2.0.x86_64-linux-musl.tar.gz"
[[lrslib]]
arch = "x86_64"
git-tree-sha1 = "a103f27d7652d5a4be10ef8416697cb7444b236c"
os = "freebsd"

    [[lrslib.download]]
    sha256 = "3e210b9538eef4078d7545cde0a8c862bcb1f0c52fb7bd92e809a4065b9e2566"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.2.0+0/lrslib.v0.2.0.x86_64-unknown-freebsd.tar.gz"
[[lrslib]]
arch = "x86_64"
git-tree-sha1 = "fa82a6d9921a7fb98739b4a9de903a0c07278e85"
os = "windows"

    [[lrslib.download]]
    sha256 = "7c41a8125bed9033564d2190bacfce6d7d60c8367f4271aeb495b7bde726f0d9"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.2.0+0/lrslib.v0.2.0.x86_64-w64-mingw32.tar.gz"
