[[lrslib]]
arch = "aarch64"
git-tree-sha1 = "fc0ebe4335f1c315d33f0bf3172a7f719d0c4056"
libc = "glibc"
os = "linux"

    [[lrslib.download]]
    sha256 = "e9e1d3e0bef0372df205145dd05691cdc1a377f8e1b28007aa1b6774265661e7"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+3/lrslib.v0.1.0.aarch64-linux-gnu.tar.gz"
[[lrslib]]
arch = "aarch64"
git-tree-sha1 = "d6a7a52e4314643f7c42be889f0dea8ffa6a255f"
libc = "musl"
os = "linux"

    [[lrslib.download]]
    sha256 = "6c9b9f9eb664fc07a39686cba8d2b0bcce3068ffc0c61e5f2725ff77577e8b71"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+3/lrslib.v0.1.0.aarch64-linux-musl.tar.gz"
[[lrslib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "33293772c906f2f3249175235d80155ba2e005e2"
libc = "glibc"
os = "linux"

    [[lrslib.download]]
    sha256 = "b3a6faa7646684577efd98c8dd196351abd0e8ac97518ee4c476f9d270e4305c"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+3/lrslib.v0.1.0.armv7l-linux-gnueabihf.tar.gz"
[[lrslib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b15393410f3ac3fb5fdab163715cacabd303e23b"
libc = "musl"
os = "linux"

    [[lrslib.download]]
    sha256 = "31ca6ca29cbe2315404a4b7840fa78b2c9aaf46bde0f4cf172ed1a6fd7e3f960"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+3/lrslib.v0.1.0.armv7l-linux-musleabihf.tar.gz"
[[lrslib]]
arch = "i686"
git-tree-sha1 = "6855921f46df26342214c9bbe563218d46c7f36b"
libc = "glibc"
os = "linux"

    [[lrslib.download]]
    sha256 = "95c977195cf31053fbceb54ba63b1fe42a6990c3d6fed1e911eddcd78fe436d6"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+3/lrslib.v0.1.0.i686-linux-gnu.tar.gz"
[[lrslib]]
arch = "i686"
git-tree-sha1 = "6b221a80550bbe066f68d5f14f2d51885e09bee1"
libc = "musl"
os = "linux"

    [[lrslib.download]]
    sha256 = "bbad078a6fd33312e5415e629e130b365d8454335b8e877cae382fcbf44907c4"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+3/lrslib.v0.1.0.i686-linux-musl.tar.gz"
[[lrslib]]
arch = "i686"
git-tree-sha1 = "6721092f3c83c3cdd359d9e3d23a811f747e7a20"
os = "windows"

    [[lrslib.download]]
    sha256 = "ec8bb1850621b2902abfb7317be52de6df1810e4f04cf020ad8fa99f89a298d3"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+3/lrslib.v0.1.0.i686-w64-mingw32.tar.gz"
[[lrslib]]
arch = "powerpc64le"
git-tree-sha1 = "9f3caed361f252dbab0b53a3097cc23dbdd844b5"
libc = "glibc"
os = "linux"

    [[lrslib.download]]
    sha256 = "a0519bc830e1511ee87a9787a6beb1e455ebadab33138ff239d3091b73675123"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+3/lrslib.v0.1.0.powerpc64le-linux-gnu.tar.gz"
[[lrslib]]
arch = "x86_64"
git-tree-sha1 = "4c3118ad252e9ae70ecbf52500cfbd60618a3eaf"
os = "macos"

    [[lrslib.download]]
    sha256 = "1e7a841c10482153aa06ee1a6e733f8f9cd11f50e144c4b6ef9d857c665cf966"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+3/lrslib.v0.1.0.x86_64-apple-darwin.tar.gz"
[[lrslib]]
arch = "x86_64"
git-tree-sha1 = "dda60ab713d514da368f67a6a215ab908e8001af"
libc = "glibc"
os = "linux"

    [[lrslib.download]]
    sha256 = "f95444af05c2d53d08c5aa72edce133d0d0a8244b27dcb94b6d418a170813b86"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+3/lrslib.v0.1.0.x86_64-linux-gnu.tar.gz"
[[lrslib]]
arch = "x86_64"
git-tree-sha1 = "6be1423648e22e82dede70b02cb2341ed2d0a845"
libc = "musl"
os = "linux"

    [[lrslib.download]]
    sha256 = "ed2caa9a02193ea3ba3a7b8b16573982f8e6123cea50d75c247dc563597d2dd3"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+3/lrslib.v0.1.0.x86_64-linux-musl.tar.gz"
[[lrslib]]
arch = "x86_64"
git-tree-sha1 = "732013648ce88affba42280df341c5f162a528b3"
os = "freebsd"

    [[lrslib.download]]
    sha256 = "9836169ca9df650b366ac62d171c6d9f1e2432f5c078b9aba0f6c703d9c41636"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+3/lrslib.v0.1.0.x86_64-unknown-freebsd.tar.gz"
[[lrslib]]
arch = "x86_64"
git-tree-sha1 = "8b13ac79b04ff1f6d1b5b948c2530a91d1df1a41"
os = "windows"

    [[lrslib.download]]
    sha256 = "dc10f0b1d9a8225f9b2bac546b82ad48bff6f60937f581a9e5cbf962aabd0e63"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.1.0+3/lrslib.v0.1.0.x86_64-w64-mingw32.tar.gz"
