[[lrslib]]
arch = "aarch64"
git-tree-sha1 = "147e970affa291962652d2214c375de307eec540"
libc = "glibc"
os = "linux"

    [[lrslib.download]]
    sha256 = "7ab4b11a8ba86658d21a9bebfed51a99390ffe4d57d311055e064bbff012c003"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.3.2+0/lrslib.v0.3.2.aarch64-linux-gnu.tar.gz"
[[lrslib]]
arch = "aarch64"
git-tree-sha1 = "89607277b374739c8c8317343dfe87187d940e6e"
libc = "musl"
os = "linux"

    [[lrslib.download]]
    sha256 = "8b50acbced2fc95849379b1a24361db10b14ebc92ce2a55b252479532bbe8ce5"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.3.2+0/lrslib.v0.3.2.aarch64-linux-musl.tar.gz"
[[lrslib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "acb422fcdf7800873bb7c8461b251cf4f2e6f394"
libc = "glibc"
os = "linux"

    [[lrslib.download]]
    sha256 = "2560e310952c145e8f85cae6009542308104625798b0e903eca3026eae48afb4"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.3.2+0/lrslib.v0.3.2.armv7l-linux-gnueabihf.tar.gz"
[[lrslib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9085e74c68dd377005320e46115d103fafb8672a"
libc = "musl"
os = "linux"

    [[lrslib.download]]
    sha256 = "fd54fbafd1c891a4710998afb777dff05fa1182c8a0091a5606e0f461023c6f0"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.3.2+0/lrslib.v0.3.2.armv7l-linux-musleabihf.tar.gz"
[[lrslib]]
arch = "i686"
git-tree-sha1 = "568874b8332004997a3903d8148bcb89d545bd5d"
libc = "glibc"
os = "linux"

    [[lrslib.download]]
    sha256 = "0ed9d8ddeed356a35affe848bf6b95a3a394f8dcae0907ccabc06386e90f4862"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.3.2+0/lrslib.v0.3.2.i686-linux-gnu.tar.gz"
[[lrslib]]
arch = "i686"
git-tree-sha1 = "c3056c8db9a1bd705338c5d21099f982f8991ef9"
libc = "musl"
os = "linux"

    [[lrslib.download]]
    sha256 = "704b75698f5e4b5b23599028b04f58c7078954c29e48621fc31b4d4d84671cc3"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.3.2+0/lrslib.v0.3.2.i686-linux-musl.tar.gz"
[[lrslib]]
arch = "i686"
git-tree-sha1 = "eb21422153d17102a6ad1b3b6d8179e1bae5970a"
os = "windows"

    [[lrslib.download]]
    sha256 = "70a668d56eeec5768464aba92d7ca72a56a03cddd1f1a4d2475eadefdaf566a0"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.3.2+0/lrslib.v0.3.2.i686-w64-mingw32.tar.gz"
[[lrslib]]
arch = "powerpc64le"
git-tree-sha1 = "6f9732240f5985515a3825a08932865445ee7cb2"
libc = "glibc"
os = "linux"

    [[lrslib.download]]
    sha256 = "a85faad3be387d2b0c0c8f6f3d9b4707f46d3b49c4dc9ea9969f54473f38e423"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.3.2+0/lrslib.v0.3.2.powerpc64le-linux-gnu.tar.gz"
[[lrslib]]
arch = "x86_64"
git-tree-sha1 = "799ffd678078a3fbb16bbafe54e3e6c1e702d41e"
os = "macos"

    [[lrslib.download]]
    sha256 = "69140e6339c4e36e63883a8770610d2efc370d61511e9ec2d406da4612ab67e6"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.3.2+0/lrslib.v0.3.2.x86_64-apple-darwin.tar.gz"
[[lrslib]]
arch = "x86_64"
git-tree-sha1 = "803e0d387a4507ef54da2902aa873a9c98bd49f5"
libc = "glibc"
os = "linux"

    [[lrslib.download]]
    sha256 = "bd0bcd969cdb2ecbfa36ae1b440c90f092f174390a468ad4a66ac3a5a0547c67"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.3.2+0/lrslib.v0.3.2.x86_64-linux-gnu.tar.gz"
[[lrslib]]
arch = "x86_64"
git-tree-sha1 = "0bb3e369dba8149aacf603f536e43a05551ecec5"
libc = "musl"
os = "linux"

    [[lrslib.download]]
    sha256 = "f234b63aeb4a6ba344d0cade95d52f381d4c56e5fb598a268dcd0aed71f1dc80"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.3.2+0/lrslib.v0.3.2.x86_64-linux-musl.tar.gz"
[[lrslib]]
arch = "x86_64"
git-tree-sha1 = "0cd71a73949cb47fcb71a8200d141692f7806890"
os = "freebsd"

    [[lrslib.download]]
    sha256 = "2c378eb223743a102ab3e97e4e0578ab0a45985dcf84121384a52ae6b0e28225"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.3.2+0/lrslib.v0.3.2.x86_64-unknown-freebsd.tar.gz"
[[lrslib]]
arch = "x86_64"
git-tree-sha1 = "b6a2f7991824f9a923e66e2c3133ca4388dc6960"
os = "windows"

    [[lrslib.download]]
    sha256 = "b974f7b5aad37044190aa607fc53fe6be5d73ca85bb715a0d76aa7298dc5b0d3"
    url = "https://github.com/JuliaBinaryWrappers/lrslib_jll.jl/releases/download/lrslib-v0.3.2+0/lrslib.v0.3.2.x86_64-w64-mingw32.tar.gz"
