# Autogenerated wrapper script for lrslib_jll for x86_64-w64-mingw32
export liblrs, liblrsnash, lrs, lrsnash

using GMP_jll
JLLWrappers.@generate_wrapper_header("lrslib")
JLLWrappers.@declare_library_product(liblrs, "liblrs-0.dll")
JLLWrappers.@declare_library_product(liblrsnash, "liblrsnash.dll")
JLLWrappers.@declare_executable_product(lrs)
JLLWrappers.@declare_executable_product(lrsnash)
function __init__()
    JLLWrappers.@generate_init_header(GMP_jll)
    JLLWrappers.@init_library_product(
        liblrs,
        "bin\\liblrs-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblrsnash,
        "bin\\liblrsnash.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        lrs,
        "bin\\lrs.exe",
    )

    JLLWrappers.@init_executable_product(
        lrsnash,
        "bin\\lrsnash.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
