# Autogenerated wrapper script for lrslib_jll for x86_64-apple-darwin
export liblrs, liblrsnash, lrs, lrsnash

using GMP_jll
JLLWrappers.@generate_wrapper_header("lrslib")
JLLWrappers.@declare_library_product(liblrs, "@rpath/liblrs.0.dylib")
JLLWrappers.@declare_library_product(liblrsnash, "@rpath/liblrsnash.dylib")
JLLWrappers.@declare_executable_product(lrs)
JLLWrappers.@declare_executable_product(lrsnash)
function __init__()
    JLLWrappers.@generate_init_header(GMP_jll)
    JLLWrappers.@init_library_product(
        liblrs,
        "lib/liblrs.0.0.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblrsnash,
        "lib/liblrsnash.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        lrs,
        "bin/lrs",
    )

    JLLWrappers.@init_executable_product(
        lrsnash,
        "bin/lrsnash",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
